version: "3.9"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on: 
      - flask
    volumes:
      - frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  flask:
    build: ./app-code
    container_name: flask-app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-app
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge 
volumes:
  frontend:
  redis-data:
