on:
  push:
    branches:                                                                     - dev

jobs:
  print-hello:
    runs-on: ubuntu-latest

    steps:
      - name: print hello
        run: |
          echo "Hello, Github Actions!"   
